#!/bin/sh

if test -f /tmp/packing/scripts/user/install_software
  then	 
  /tmp/packing/scripts/user/install_software
 fi

cd  ^^code_destination^^

if test -f Gemfile
 then
   bundle -standalone
fi


if test -f /tmp/packing/scripts/user/rakes
 then
    /tmp/packing/scripts/user/rakes
fi

